import { Component, OnInit, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ToasterService } from 'angular2-toaster';
import { KingBDialogalertService } from 'src/app/king/bootstrap/king-b-dialog-alert/king-b-dialogalert.service';

@Component({
  selector: 'teste-app',
  templateUrl: './teste.component.html'
})
export class TesteComponent implements OnInit {
  constructor(private kingBDialogalert: KingBDialogalertService, private toasterService: ToasterService, public _FormBuilder: FormBuilder) {
  }


  abrir() {
    this.kingBDialogalert.showKingDialog('danger', '', 'Teste de Mensagem').then(() => {
      this.toasterService.pop('error', 'Atenção', 'Retornado');
    })
  }
  formulario: FormGroup;

  ngOnInit() {
    this.formulario = this._FormBuilder.group({
      'checkgroup': [null, Validators.required],
      'checkbox': [null, Validators.required],
      'consulta': [null, Validators.required],
      'datetime': [null, Validators.required],
      'list': [null, Validators.required],
      'select': [null, Validators.required],
      'time': [null, Validators.required],
      'date': [null, Validators.required],
      'image': [null, Validators.required],
      'email': [null, [Validators.required, Validators.email]],
      'number': [null, Validators.required],
      'money': [null, Validators.required],
      'textarea': [null, Validators.required],
      'passwd': [null, Validators.required],
      'text': [null, Validators.required],
      'phone': [null, Validators.required],
    });

  }

  validate(evento) {    debugger
		this.formulario.get(evento.currentTarget.type).setErrors({ valid: false });
		this.formulario.get(evento.currentTarget.type).setValue(evento.target.value);
    
  }

  public valuesSelect = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize	',
    'Benin	',
    'Bhutan	',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil	',
    'Brunei	',
    'Bulgaria',
    'Burkina Faso',
    'Burund',
    'Côte d`Ivoire',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada	',
    'Central African Republic',
    'Chad	',
    'Chile	',
    'China	',
    'Colombia',
    'Comoros	',
    'Congo (Congo-Brazzaville)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus	',
    'Czechia',
    'Democratic Republic of the',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republi',
    'Ecuador',
    'Egypt	',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia	',
    'Eswatini',
    'Ethiopia',
    'Fiji	',
    'Finland',
    'France	',
    'Gabon	',
    'Gambia	',
    'Georgia',
    'Germany',
    'Ghana	',
    'Greece	',
    'Grenada',
    'Guatemala',
    'Guinea	',
    'Guinea-Bissau',
    'Guyana	',
    'Haiti	',
    'Holy See',
    'Honduras',
    'Hungary',
    'Iceland',
    'India	',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel	',
    'Italy	',
    'Jamaica',
    'Japan	',
    'Jordan	',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives	',
    'Mali',
    'Malta',
    'Marshall',
    'Mauritania',
    'Mauritius',
    'Mexico	',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru	',
    'Nepal	',
    'Netherlands',
    'New Zealand',
    'Nicaragua	',
    'Niger	',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman	',
    'Pakistan',
    'Palau   ',
    'Palestine State',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar	',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grena',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia	',
    'Seychelles',
    'Sierra Leon',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname	',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan	',
    'Tanzania	',
    'Thailand	',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine	',
    'United Arab Emirates',
    'United Kingdom',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen	',
    'Zambia	',
    'Zimbabwe',
  ]
}
